# Generated by Django 2.2.17 on 2021-03-07 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_number', models.IntegerField()),
                ('client_name', models.CharField(max_length=100)),
                ('project_ref', models.CharField(max_length=100)),
                ('employee_name', models.CharField(max_length=100)),
                ('hours', models.FloatField()),
                ('date', models.DateField()),
                ('work_type', models.CharField(max_length=100)),
                ('work_description', models.TextField()),
            ],
        ),
    ]
